#!/usr/bin/env bash
# insightd one-command install
# Usage:  curl -sSL https://insightd.org/install.sh | bash
# Custom path:  INSIGHTD_DIR=/opt/insightd curl -sSL https://insightd.org/install.sh | bash
#
# What it does:
#   1. verifies Docker + Compose v2 are present
#   2. downloads docker-compose.hub.yml to $INSIGHTD_DIR
#   3. generates a .env with an openssl-random MQTT password (idempotent)
#   4. docker compose up -d  (Mosquitto + Hub + local Agent)
#   5. polls until the hub is reachable, then prints next steps
#
# Source:  https://github.com/goldenproductions/insightd.org/blob/main/public/install.sh

set -euo pipefail

DIR="${INSIGHTD_DIR:-$HOME/insightd}"
COMPOSE_URL="https://raw.githubusercontent.com/goldenproductions/insightd/main/docker-compose.hub.yml"

log() { printf '  %s\n' "$*"; }
err() { printf '\n  error: %s\n\n' "$*" >&2; }

# 1. preflight
command -v docker >/dev/null 2>&1 || {
  err "Docker not found. Install Docker Engine from https://docs.docker.com/engine/install/ and re-run."
  exit 1
}
docker compose version >/dev/null 2>&1 || {
  err "Docker Compose v2 not found. Install the compose plugin and re-run."
  exit 1
}
command -v curl >/dev/null 2>&1 || { err "curl is required."; exit 1; }
command -v openssl >/dev/null 2>&1 || { err "openssl is required (for password generation)."; exit 1; }

echo ""
log "insightd installer → $DIR"
echo ""

# 2. scaffold install dir
mkdir -p "$DIR"
cd "$DIR"

# 3. fetch compose file (always overwrite — it's our contract, not user state)
log "fetching docker-compose.hub.yml"
curl -fsSL -o docker-compose.hub.yml "$COMPOSE_URL"

# 4. generate .env idempotently
if [ ! -f .env ]; then
  log "generating .env with a new MQTT password"
  MQTT_PASS="$(openssl rand -hex 24)"
  cat > .env <<EOF
# Generated by insightd installer on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file — it is the source of truth for your MQTT credentials.
INSIGHTD_MQTT_USER=insightd
INSIGHTD_MQTT_PASS=$MQTT_PASS
INSIGHTD_HOST_ID=hub-server
INSIGHTD_ALLOW_UPDATES=true
INSIGHTD_ALLOW_ACTIONS=true
EOF
  chmod 600 .env
else
  log ".env already exists — leaving it alone"
fi

# 5. bring up the stack
log "pulling images"
docker compose -f docker-compose.hub.yml pull --quiet 2>/dev/null || true
log "starting containers"
docker compose -f docker-compose.hub.yml up -d

# 6. wait for the hub to respond, then print the banner
log "waiting for hub to come up"
for _ in $(seq 1 30); do
  if curl -fsS http://localhost:3000/api/setup/status >/dev/null 2>&1; then
    IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
    [ -z "${IP:-}" ] && IP="localhost"
    echo ""
    echo "  ✓ insightd is running"
    echo ""
    echo "    Open  http://$IP:3000"
    echo "    Config  $DIR/.env  (protects your MQTT password — back it up)"
    echo ""
    echo "  Next: finish the setup wizard, then add remote agents from"
    echo "        the 'Add Agent' page in the web UI."
    echo ""
    exit 0
  fi
  sleep 2
done

err "hub didn't respond within 60s"
echo "  Check logs: docker compose -f $DIR/docker-compose.hub.yml logs hub" >&2
exit 1
